import { fromPosixPath as furiFromPosixPath } from "furi";
import sysPath from "path";

import { PROJECT_ROOT } from "./locations.js";

export function emitJsfl(scripts: Iterable<[string, string]>): string {
  const data: Record<string, string> = Object.create(null);
  for (const [absIncludePath, absSwfPath] of scripts) {
    const includePath = sysPath.posix.relative(PROJECT_ROOT, absIncludePath);
    const relSwfPath = sysPath.posix.relative(PROJECT_ROOT, absSwfPath);
    const swfFuri = furiFromPosixPath(sysPath.posix.join("/", relSwfPath));
    data[JSON.stringify(includePath)] = swfFuri.toString();
  }

  return `// Auto-generated by \`emit-jsfl.ts\`: do not edit this file directly
var data = ${JSON.stringify(data, null, 2)};

// https://github.com/haysclark/flashcommand/blob/master/osx/src/flashcommand
var sourceFile = "file:///.tools/template/template.xfl";
var doc = fl.openDocument(sourceFile);

for (var quotedScriptPath in data) {
  doc.getTimeline().layers[0].frames[0].actionScript = "#include " + quotedScriptPath + "\\n";
  doc.exportSWF(data[quotedScriptPath], true);
}

fl.getDocumentDOM().close(false);
fl.quit(false);
`;
}
